git_url: "https://github.com/Polokalap/plugin.git"
module_folder: "tp plugin"
name: "tp plugin"
description: "This is an example plugin bada bing bada boom."
version: 1
author: "Polokalap"
license: "GPLv3.0"
website: "https://github.com/Polokalap"
