git_url: "https://github.com/Polokalap/plugin/plugin.git"
module_folder: "tp plugin"
name: "tp plugin"
description: "Simple tpa plugin."
version: 1
author: "Polokalap"
license: "GPLv3.0"
website: "https://github.com/Polokalap"
